variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

# Official docker compose image.
image:
  name: docker/compose:1.24.1
  entrypoint: ["/bin/sh", "-c"]

services:
  - docker:18.09.7-dind

build-js:
  stage: build
  artifacts:
    paths:
      - static
  script:
    - docker-compose run -T --entrypoint '' --rm webpack npm run build
