PROJECT_URL: https://your-hostname.tld
SCHEMA_URL: https://schema.your-hostname.tld

MAILS_FROM: no-reply@openbikebox.de
ADMINS:
  - admin@openbikebox.de

SECRET_KEY: please-insert-random-key
SQLALCHEMY_DATABASE_URI: mysql+pymysql://please-insert-user:please-insert-password@mysql/please-insert-database

MAIL_SERVER: please-insert-mail-hostname
MAIL_USERNAME: please-insert-mail-user
MAIL_PASSWORD: please-insert-mail-password

CELERY_BROKER_URL: amqp://please-insert-rabbitmq-hostname
SOCKETIO_QUEUE: amqp://please-insert-rabbitmq-hostname
