version: '3.7'

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - mysql
      - rabbitmq
    user: ${CURRENT_UID}
    environment:
      FLASK_ENV: development
    command: ["python3", "runserver.py"]

  worker:
    build:
      context: .
      dockerfile: Dockerfile.flask
    volumes:
      - .:/app
    depends_on:
      - mysql
      - rabbitmq
    user: ${CURRENT_UID}
    environment:
      FLASK_ENV: development
    command: ["/app/celery_dev.sh"]

  webpack:
    image: node:12
    ports:
      - 8888:8888
    working_dir: /app
    volumes:
      - .:/app
    init: true
    command: ["/app/webpack_dev.sh"]
    user: ${CURRENT_UID}

  mysql:
    image: mariadb
    volumes:
      - .:/app
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: open-bike-box-backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8082:80
    environment:
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_HOST: mysql

  redis:
    image: redis

  rabbitmq:
    image: rabbitmq:latest

volumes:
  mysql:

