version: '3'
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - mysql
      - rabbitmq
    user: ${CURRENT_UID}
    command: ["python3", "runserver.py"]

  worker:
    build:
      context: .
      dockerfile: Dockerfile.flask
    volumes:
      - .:/app
    depends_on:
      - mysql
      - rabbitmq
    user: ${CURRENT_UID}
    command: ["/app/celery_dev.sh"]

  mysql:
    image: mariadb
    container_name: open-bike-box-backend-mysql
    volumes:
      - .:/app
      - open_bike_box_backend_mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: open-bike-box-backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8082:80
    environment:
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_HOST: mysql

  redis:
    image: redis

  rabbitmq:
    image: rabbitmq:latest

volumes:
  open_bike_box_backend_mysql:

