"""user login related

Revision ID: eb713944b6c6
Revises: 2671af663659
Create Date: 2021-06-21 15:46:03.936193

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb713944b6c6'
down_revision = '2671af663659'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.Enum('admin', 'operator', name='userrole'), nullable=True))
    op.add_column('user', sa.Column('first_name', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=255), nullable=True))
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'firstname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firstname', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=True))
    op.add_column('user', sa.Column('lastname', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=True))
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
