"""future booking, location type, typo

Revision ID: 0fdb569171cc
Revises: cc9ecd78e189
Create Date: 2021-06-01 12:02:26.682980

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0fdb569171cc'
down_revision = 'cc9ecd78e189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hardware', sa.Column('future_booking', sa.Boolean(), nullable=True))
    op.add_column('location', sa.Column('type', sa.Enum('bikebox', 'cargobike', name='locationtype'), nullable=True))
    op.add_column('location', sa.Column('twentyfourseven', sa.Boolean(), nullable=True))
    op.drop_column('location', 'twentyforseven')
    op.add_column('operator', sa.Column('future_booking', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operator', 'future_booking')
    op.add_column('location', sa.Column('twentyforseven', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('location', 'twentyfourseven')
    op.drop_column('location', 'type')
    op.drop_column('hardware', 'future_booking')
    # ### end Alembic commands ###
