"""init

Revision ID: fcb9d9a33687
Revises: 
Create Date: 2021-02-08 15:20:10.354860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcb9d9a33687'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('uid', sa.String(length=64), nullable=False),
    sa.Column('request_uid', sa.String(length=64), nullable=False),
    sa.Column('session', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.BigInteger(), nullable=True),
    sa.Column('location_id', sa.BigInteger(), nullable=True),
    sa.Column('resource_access_id', sa.BigInteger(), nullable=True),
    sa.Column('pricegroup_id', sa.BigInteger(), nullable=True),
    sa.Column('operator_id', sa.BigInteger(), nullable=True),
    sa.Column('resource_cache', sa.Text(), nullable=True),
    sa.Column('location_cache', sa.Text(), nullable=True),
    sa.Column('resource_access_cache', sa.Text(), nullable=True),
    sa.Column('pricegroup_cache', sa.Text(), nullable=True),
    sa.Column('operator_cache', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('valid_till', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('begin', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('pin', sa.String(length=4), nullable=True),
    sa.Column('status', sa.Enum('reserved', 'booked', 'timeouted', 'cancelled', 'disrupted', name='actionstatus'), nullable=False),
    sa.Column('value_gross', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('value_net', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('value_tax', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid'),
    mysql_charset='utf8',
    mysql_collate='utf8_unicode_ci'
    )
    op.create_table('file',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('mimetype', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_unicode_ci'
    )
    op.create_table('hardware',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_unicode_ci'
    )
    op.create_table('location',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('operator_id', sa.BigInteger(), nullable=True),
    sa.Column('photo_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('lon', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('postalcode', sa.String(length=255), nullable=True),
    sa.Column('locality', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['operator.id'], use_alter=True),
    sa.ForeignKeyConstraint(['photo_id'], ['file.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_unicode_ci'
    )
    op.create_index(op.f('ix_location_slug'), 'location', ['slug'], unique=True)
    op.create_table('operator',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('logo_id', sa.BigInteger(), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('postalcode', sa.String(length=255), nullable=True),
    sa.Column('locality', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['logo_id'], ['file.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_unicode_ci'
    )
    op.create_table('option',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=True),
    sa.Column('type', sa.Enum('string', 'date', 'datetime', 'integer', 'decimal', 'dict', 'list'), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_unicode_ci'
    )
    op.create_index(op.f('ix_option_key'), 'option', ['key'], unique=True)
    op.create_table('pricegroup',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('operator_id', sa.BigInteger(), nullable=True),
    sa.Column('fee_hour', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('fee_day', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('fee_week', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('fee_month', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('fee_year', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['operator.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_unicode_ci'
    )
    op.create_table('resource',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=True),
    sa.Column('pricegroup_id', sa.BigInteger(), nullable=True),
    sa.Column('hardware_id', sa.BigInteger(), nullable=True),
    sa.Column('resource_group_id', sa.BigInteger(), nullable=True),
    sa.Column('resource_access_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('internal_identifier', sa.String(length=255), nullable=True),
    sa.Column('user_identifier', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('free', 'taken', 'reserved', 'inactive', 'faulted', name='resourcestatus'), nullable=True),
    sa.Column('unavailable_until', sa.DateTime(), nullable=True),
    sa.Column('installed_at', sa.DateTime(), nullable=True),
    sa.Column('maintenance_from', sa.DateTime(), nullable=True),
    sa.Column('maintenance_till', sa.DateTime(), nullable=True),
    sa.Column('polygon_top', sa.Float(), nullable=True),
    sa.Column('polygon_right', sa.Float(), nullable=True),
    sa.Column('polygon_bottom', sa.Float(), nullable=True),
    sa.Column('polygon_left', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['hardware_id'], ['hardware.id'], use_alter=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], use_alter=True),
    sa.ForeignKeyConstraint(['pricegroup_id'], ['pricegroup.id'], use_alter=True),
    sa.ForeignKeyConstraint(['resource_access_id'], ['resource_access.id'], use_alter=True),
    sa.ForeignKeyConstraint(['resource_group_id'], ['resource_group.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_unicode_ci'
    )
    op.create_index(op.f('ix_resource_slug'), 'resource', ['slug'], unique=True)
    op.create_table('resource_access',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=True),
    sa.Column('internal_identifier', sa.String(length=255), nullable=True),
    sa.Column('salt', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_unicode_ci'
    )
    op.create_table('resource_group',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('internal_identifier', sa.String(length=255), nullable=True),
    sa.Column('user_identifier', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'faulted', name='resourcegroupstatus'), nullable=True),
    sa.Column('max_bookingdate', sa.Integer(), nullable=True),
    sa.Column('installed_at', sa.DateTime(), nullable=True),
    sa.Column('maintenance_from', sa.DateTime(), nullable=True),
    sa.Column('maintenance_till', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_unicode_ci'
    )
    op.create_index(op.f('ix_resource_group_slug'), 'resource_group', ['slug'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('operator_id', sa.BigInteger(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('login_datetime', sa.DateTime(), nullable=True),
    sa.Column('last_login_datetime', sa.DateTime(), nullable=True),
    sa.Column('login_ip', sa.String(length=64), nullable=True),
    sa.Column('last_login_ip', sa.String(length=64), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=True),
    sa.Column('last_failed_login_count', sa.Integer(), nullable=True),
    sa.Column('firstname', sa.String(length=255), nullable=True),
    sa.Column('lastname', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('postalcode', sa.String(length=255), nullable=True),
    sa.Column('locality', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('language', sa.Enum('de', 'en'), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('mobile', sa.String(length=255), nullable=True),
    sa.Column('capabilities', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['operator.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_unicode_ci'
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('resource_group_image',
    sa.Column('resource_group_id', sa.BigInteger(), nullable=True),
    sa.Column('file_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.ForeignKeyConstraint(['resource_group_id'], ['resource_group.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_group_image')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_resource_group_slug'), table_name='resource_group')
    op.drop_table('resource_group')
    op.drop_table('resource_access')
    op.drop_index(op.f('ix_resource_slug'), table_name='resource')
    op.drop_table('resource')
    op.drop_table('pricegroup')
    op.drop_index(op.f('ix_option_key'), table_name='option')
    op.drop_table('option')
    op.drop_table('operator')
    op.drop_index(op.f('ix_location_slug'), table_name='location')
    op.drop_table('location')
    op.drop_table('hardware')
    op.drop_table('file')
    op.drop_table('action')
    # ### end Alembic commands ###
