"""booking base url

Revision ID: 2671af663659
Revises: 59972fce0831
Create Date: 2021-06-10 09:58:59.712469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2671af663659'
down_revision = '59972fce0831'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('booking_base_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'booking_base_url')
    # ### end Alembic commands ###
