"""additional texts

Revision ID: aaf8cfeb6ba5
Revises: eb713944b6c6
Create Date: 2021-07-23 12:52:01.459077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaf8cfeb6ba5'
down_revision = 'eb713944b6c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('terms_and_conditions', sa.String(length=255), nullable=True))
    op.add_column('location', sa.Column('bike_size_information', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'bike_size_information')
    op.drop_column('location', 'terms_and_conditions')
    # ### end Alembic commands ###
