"""alert relationships

Revision ID: cc9ecd78e189
Revises: eca8c5dd7d03
Create Date: 2021-05-29 08:01:03.453071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc9ecd78e189'
down_revision = 'eca8c5dd7d03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_alert',
    sa.Column('location_id', sa.BigInteger(), nullable=True),
    sa.Column('alert_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], )
    )
    op.create_table('resource_alert',
    sa.Column('resource_id', sa.BigInteger(), nullable=True),
    sa.Column('alert_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], )
    )
    op.add_column('alert', sa.Column('active', sa.Boolean(), nullable=True))
    op.drop_constraint('alert_ibfk_1', 'alert', type_='foreignkey')
    op.drop_constraint('alert_ibfk_3', 'alert', type_='foreignkey')
    op.drop_column('alert', 'resource_id')
    op.drop_column('alert', 'location_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('geometry_index', 'location', ['geometry'], unique=False)
    op.add_column('alert', sa.Column('location_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.add_column('alert', sa.Column('resource_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.create_foreign_key('alert_ibfk_3', 'alert', 'resource', ['resource_id'], ['id'])
    op.create_foreign_key('alert_ibfk_1', 'alert', 'location', ['location_id'], ['id'])
    op.drop_column('alert', 'active')
    op.drop_table('resource_alert')
    op.drop_table('location_alert')
    # ### end Alembic commands ###
