"""osm id keys

Revision ID: f6c014961b4f
Revises: 2bdf858db97c
Create Date: 2021-03-12 16:55:02.095528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6c014961b4f'
down_revision = '2bdf858db97c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('osm_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'location', 'file', ['photo_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'location', 'operator', ['operator_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'operator', 'file', ['logo_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'pricegroup', 'operator', ['operator_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'resource', 'pricegroup', ['pricegroup_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'resource', 'hardware', ['hardware_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'resource', 'resource_group', ['resource_group_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'resource', 'resource_access', ['resource_access_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'resource', 'location', ['location_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'resource_access', 'location', ['location_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'resource_group', 'location', ['location_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'user', 'operator', ['operator_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'resource_group', type_='foreignkey')
    op.drop_constraint(None, 'resource_access', type_='foreignkey')
    op.drop_constraint(None, 'resource', type_='foreignkey')
    op.drop_constraint(None, 'resource', type_='foreignkey')
    op.drop_constraint(None, 'resource', type_='foreignkey')
    op.drop_constraint(None, 'resource', type_='foreignkey')
    op.drop_constraint(None, 'resource', type_='foreignkey')
    op.drop_constraint(None, 'pricegroup', type_='foreignkey')
    op.drop_constraint(None, 'operator', type_='foreignkey')
    op.drop_constraint(None, 'location', type_='foreignkey')
    op.drop_constraint(None, 'location', type_='foreignkey')
    op.drop_column('location', 'osm_id')
    # ### end Alembic commands ###
