"""10 years

Revision ID: 02d3509269d2
Revises: 2449b459e676
Create Date: 2022-02-16 09:33:29.820834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02d3509269d2'
down_revision = '2449b459e676'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricegroup', sa.Column('fee_ten_years', sa.Numeric(precision=7, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pricegroup', 'fee_ten_years')
    # ### end Alembic commands ###
